### ISSUE TITLE
Upgrade to Livewire 3

### ISSUE THREAD

**Issue by django23** [mattlibera/livewire-flash#28]
Hi,

Any plans on updating it for Livewire3?

Kind regards,

**Comment by mattlibera** [comment]
hi @django23 , sorry for the massive delay here. i've just merged a PR and bumped deps for Laravel 11 and Livewire 3. hope that helps!

see: #30 and v0.8 release

**Comment by django23** [comment]
You are excused ;)
No really, thanks.
