### ISSUE TITLE
Livewire 2.x

### ISSUE THREAD

**Issue by jjrohrer** [mattlibera/livewire-flash#6]
(I was trying 
composer require mattlibera/livewire-flash

Using version ^0.3.1 for mattlibera/livewire-flash
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: livewire/livewire[1.x-dev, v2.1.2].
    - Can only install one of: livewire/livewire[v2.1.2, 1.x-dev].
    - Can only install one of: livewire/livewire[1.x-dev, v2.1.2].
    - mattlibera/livewire-flash v0.3.1 requires livewire/livewire ^1.2 -> satisfiable by livewire/livewire[1.x-dev].
    - Installation request for mattlibera/livewire-flash ^0.3.1 -> satisfiable by mattlibera/livewire-flash[v0.3.1].
    - Installation request for livewire/livewire (locked at v2.1.2, required as ^2.0) -> satisfiable by livewire/livewire[v2.1.2].

Installation failed, reverting ./composer.json to its original content.

**Comment by mattlibera** [comment]
Sorry about this. I will see what I can do today to get Livewire 2.0 support. Don't think it'll be a tough lift.

**Comment by mattlibera** [comment]
@jjrohrer Should be set via #7 . Just update your requirement for this package to be `^0.4` and then `composer update mattlibera/livewire-flash` should pull it in. Let me know if that doesn't work for some reason.

**Comment by jjrohrer** [comment]
Nice!
